name: Deploy to VPS via SFTP

on:
  push:
    branches:
      - main

jobs:
  sftp-deploy:
    name: SFTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: Creepios/sftp-action@v1.0.4
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localPath: './'
          remotePath: '/var/www/html/'
